### ISSUE TITLE
inserir favicon

### ISSUE THREAD

**Issue by thomazrezende** [updatepolitics/website#41]
colocar no header de todas as páginas a tag:

<link rel="icon" type="image/png" href="layout/favicon.png" />

corrigindo o caminho, se necessário

![favicon](https://cloud.githubusercontent.com/assets/8996819/15977315/6eecd50c-2f2e-11e6-8fde-4bba98490b84.png)

**Comment by thomazrezende** [comment]
@vgeorge veja se esse serve. fiz um teste aqui e funcionou. abs
[favicon.ico.zip](https://github.com/updatepolitics/website/files/344222/favicon.ico.zip)

**Comment by vgeorge** [comment]
Ficou grande o arquivo .ico, 370 kB. Vou deixar sem por enquanto
