### ISSUE TITLE
[inglês] texto About desalinhado

### ISSUE THREAD

**Issue by beatrizdcp** [updatepolitics/website#57]
o texto ABOUT está com a configuração errada, a parte de cima está como 'justify' e a de baixo está alinhando para a esquerda

**Comment by vgeorge** [comment]
É essa parte que vc se refere? Está alinhada a esquerda, não?

![captura de tela 2016-06-29 as 21 15 53](https://cloud.githubusercontent.com/assets/329694/16473118/ca781e74-3e40-11e6-963d-4f64300b631a.png)

**Comment by beatrizdcp** [comment]
Esse tá tipo 'justify' o de baixo tá alinhando a esquerda

**Comment by vgeorge** [comment]
A imagem acima também está alinhado à esquerda, se fosse jusficado estaria como na imagem abaixo. No design original do @thomazrezende o texto está a esquerda. Vocês querem mudar todo o site para justificado?

![captura de tela 2016-07-21 as 20 41 18](https://cloud.githubusercontent.com/assets/329694/17042395/88f95ec8-4f83-11e6-9b43-b5ec09311c63.png)

**Comment by beatrizdcp** [comment]
não. eu vi, tá td certo!
