### ISSUE TITLE
clique nos BOX em DETAILS não funciona

### ISSUE THREAD

**Issue by thomazrezende** [updatepolitics/website#71]
as telas details HUB e SINAL possuem boxes coloridos com os TEMAS ou NATUREZAS. O clique nesses boxes deve redirecionar para a lista pré-filtrada pelo elemento escolhido. Deve haver tb uma barra inferior colorida: cor do elemento no BG, nome do elemento e fechar (X).

**Comment by vgeorge** [comment]
Conversando com o Tulio decidimos remover esta funcionalidade na versão atual.
